### ISSUE TITLE
There problem with Potion Cauldron mod

### ISSUE THREAD

**Issue by Sushikee** [maxoduke/Potion-Cauldron#16]
So, I use Iris shader and BSL shader and I saw the texture of potion inside of cauldron was glitchy  (pictures below for comparison)
Is there any way to fix this?

![2024-07-12_18 00 12](https://github.com/user-attachments/assets/c3bb13fd-26cc-4e67-bf47-0a4e5f242f40)
![2024-07-12_17 59 41](https://github.com/user-attachments/assets/6bbc9c3a-5316-4d09-a847-35517075d8b1)

**Comment by maxoduke** [comment]
i will try it out and see what i can do

**Comment by Sushikee** [comment]
ah thank you so much. so far other shader i use, Complementary Reimagined have no issue.

**Comment by maxoduke** [comment]
which shader are you using? could you post a link to it?
i just tried it with BSL and it works fine in my game.

![image](https://github.com/user-attachments/assets/449146ac-0d9c-4b1a-a295-24b897b5ffc1)

**Comment by Sushikee** [comment]
I am using BSL shader from Modrinth
https://modrinth.com/shader/bsl-shaders

**Comment by Sushikee** [comment]
Hey, so I already found the problem. So, the texture did not support the advanced material setting in BSL shader. I disable that and the texture fixed.
![image_2024-07-14_033346434](https://github.com/user-attachments/assets/2e791906-d04c-4962-a8f1-2e29ea748ba1)

**Comment by maxoduke** [comment]
alright. i guess it's safe to close this issue.
